### ISSUE TITLE
Remove StyleCop dependency

### ISSUE THREAD

**Issue by mlhDevelopment** [ubiety/Ubiety.Logging.Core#1]
MySql.Data [depends on](https://bugs.mysql.com/bug.php?id=98204) Ubiety.Dns.Core, which in turn depends on Ubiety.Logging.Core > StyleCop.Analyzers. If a project does not desire StyleCop it installs it and StyleCop has a default-on functionality causing the project to be analyze. Since StyleCop is not adding any functionality Dns.Core and Logging.Core can it be removed, at least as a dependency?

**Comment by mconradiesa** [comment]
Agreed - we are also having so many problems with stylecop slowing down our builds and VS highlighting everywhere since the latest Mysql.Data nuget. Wish we could remove it.

**Comment by coder2000** [comment]
I'm sorry. The analyzer is still part of the project however I have made it private so it should not be a dependency for using this library after version 1.2.0.
